export const cameraPosition = {
  general: {
    x: -32,
    y: 54,
    z: -62,
    rotateX: -2.32,
    rotateY: -0.54,
    rotateZ: -2.63,
  },
  workshop_1: {
    x: 1,
    y: 40,
    z: -10,
    rotateX: -Math.PI / 2,
    rotateY: 0,
    rotateZ: -Math.PI / 2 - 0.1,
  },
  workshop_2: {
    x: -4,
    y: 30,
    z: 24,
    rotateX: -Math.PI / 2,
    rotateY: 0,
    rotateZ: -Math.PI / 2 - 0.1,
  },
  workshop_3: {
    x: 28,
    y: 52,
    z: -15,
    rotateX: -Math.PI / 2,
    rotateY: 0,
    rotateZ: -Math.PI / 2 - 0.1,
  },
  workshop_4: {
    x: 3,
    y: 50,
    z: 8,
    rotateX: -Math.PI / 2,
    rotateY: 0,
    rotateZ: -Math.PI / 2 - 0.1,
  },
}
