// export const selectColor = '#eb5a16'
// export const selectedColor = '#df6c37'
// export const activeColor = '#dfa084'
// export const inactiveColor = '#ecd3c6'
// export const textColor = '#5c5c5c'
// export const textSelectedColor = '#222222'
// export const repairColor = '#FF0000'

export const activatedColor = '#808080'
export const selectedColor = '#8d8d8d'
export const defaultColor = '#c7c7c7'
export const inactiveColor = '#ffffff'
export const textColor = '#7c7c7c'
export const textSelectedColor = '#000000'
export const activeColor = '#00ff00'
export const serviceColor = '#f4a900'
export const repairColor = '#FF0000'
export const textRepairColor = '#580000'
